config/routes.rb
Rails.application.routes.draw do
  resources :checklist_notes, except: [:index], controller: :notes
  resources :survey_notes, except: [:index], controller: :notes
  resources :case_notes, except: [:index], controller: :notes
  resources :task_notes, except: [:index], controller: :notes
  resources :notes, except: [:index]

  resources :cases do
    member do
      get 'delete_sub_case_relation'
      get 'delete_relation'
      match 'new_relation', via: [:post, :get]
      match 'new_assign', via: [:post, :get]
      match 'new_assign_survey', via: [:post, :get]
    end
  end
  resources :attempts, :only => [:new, :create, :index]
  get 'pivot_table/index'

  get 'settings/edit'
  get 'home/index'
  root to: "home#index"
  get 'home/all_informations', as: 'all_informations'

  get 'home/pivottable'

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }

  # Routes For Normal users
  resources :core_demographics, only: [:show]
  resources :departments do
    resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :contacts do
    resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :affiliations do
    resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
  end
  resources :organizations do
    resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :other_skills
  resources :clearances
  resources :certifications
  resources :educations
  resources :languages
  resources :positions
  resources :tasks do
    member do
      post 'new_note'
      get 'add_note'
      get 'delete_sub_task_relation'
    end
  end
  resources :documents


  resources :surveys do
    member do
      post   'answer'
      get    'new_note'
      get    'edit_answer'
      post   'edit_answer'
      delete 'delete_answer'
    end

    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :survey_survey,  controller: :surveys


  # Routes For Admin
  resources :checklist_templates, controller: :checklists do
    member do
      match 'save', via: [:patch, :put, :post]
      get 'new_note'
    end
    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :users, only: [:index, :show, :destroy] do
    member do
      put 'change_password'
      put 'change_basic_info'
      post 'image_upload'
      get 'remove_image'
    end

    resources :core_demographics, only: [:create, :update]
    resources :job_details, only: [:create, :update]
    resources :user_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :employees, except: [:edit] do
    member do
      get 'log_in'
    end

    get 'home/index', as: 'home'
    resources :educations
    resources :tasks
    resources :languages
    resources :positions
    resources :other_skills
    resources :clearances
    resources :certifications
    resources :departments do
      resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :contacts do
      resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :affiliations do
      resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
    end
    resources :organizations do
      resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :documents
  end

  resources :enumerations
  resources :roles
  resources :settings, only: [:index, :create] do
    collection do
      post 'set_modules'
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  belongs_to :user
  belongs_to :case, optional: true, foreign_key: :related_to_id

  validates_presence_of :title

  scope :not_related, -> {where(related_to_id: nil)}

  has_many :document_attachments, foreign_key: :owner_id
  accepts_nested_attributes_for :document_attachments, reject_if: :all_blank, allow_destroy: true

  after_save :send_notification
  def send_notification
    UserMailer.document_notification(self).deliver_now
  end

  def document_type
    if document_type_id
      super
    else
      DocumentType.default
    end
  end

  def visible?
    User.current == user or User.current.allowed_to?(:edit_documents) or User.current.allowed_to?(:manage_documents)
  end

  def self.safe_attributes
    [:title, :description, :related_to_id, :related_to_type, :user_id, :document_type_id, :date, document_attachments_attributes: [Attachment.safe_attributes]]
  end

  def to_pdf(pdf)
    pdf.font_size(25){  pdf.text "Document ##{id}", :style => :bold}
    user.to_pdf_brief_info(pdf)
    pdf.text "<b>Title: </b> #{title}", :inline_format =>  true
    pdf.text "<b>Description: </b> #{ActionView::Base.full_sanitizer.sanitize(description)}", :inline_format =>  true
    pdf.text "<b>Document type: </b> #{document_type}", :inline_format =>  true
  end

  def for_mail
    output = ""
    output<< "<h2>Document ##{id} </h2>"
    output<< "<b>Title: </b> #{title}<br/>"
    output<< "<b>Description: </b> #{description}<br/>"
    output<< "<b>Document type: </b> #{document_type}<br/>"
    output.html_safe
  end

end

app/models/enumerations/document_type.rb
class DocumentType < Enumeration
  has_many :documents

  OptionName = :enumeration_document_type

  def option_name
    OptionName
  end

  def objects
    Document.where(:document_type_id => self.id)
  end

  def objects_count
    objects.count
  end

  def transfer_relations(to)
    objects.update_all(:document_type_id => to.id)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action  :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  # before_action :find_optional_user
  before_action :authorize, only: [:new, :create]
  before_action :authorize_edit, only: [:edit, :update]
  before_action :authorize_delete, only: [:destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.not_related.visible :view_documents
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new(user_id: @user.id,
                             related_to_id: params[:related_to],
                             related_to_type: params[:type])
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to back_url, notice: 'Document was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to back_url, notice: 'Document was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_404
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(Document.safe_attributes)
    end
  def authorize_edit
    raise Unauthorized unless @document.can?(:edit_documents, :manage_documents, :manage_roles)
  end

  def authorize_delete
    raise Unauthorized unless @document.can?(:delete_documents, :manage_documents, :manage_roles)
  end

  def back_url
    if @document.case
      @document.case
    else
      documents_url
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def back_url doc
    doc.related_to_id ? doc.case : documents_path
  end
end

app/views/documents/_form.html.erb
<fieldset>
  <legend></legend>
  <%= form_for(document, html: { class: 'form-horizontal',  :multipart => true}) do |f| %>
      <% if document.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

            <ul>
              <% document.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%= f.hidden_field :user_id %>

      <%= f.hidden_field :related_to_type %>
      <%= f.hidden_field :related_to_id %>

      <div class="form-group">
        <%= f.label t(:title), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :title , class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t(:description) , class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_area :description , class: 'form-control ckeditor' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t(:document_type), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.select :document_type_id, options_for_select(DocumentType.active.pluck(:name, :id), selected: document.document_type_id) , {} ,{class: 'form-control'} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t(:date) , class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :date , class: 'form-control date_picker' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-12">
          <%= f.label t(:attachments) , class: 'col-md-2 control-label' %>
        </div>
        <%= f.simple_fields_for :document_attachments do |attachment| %>
            <%= render 'attachments/attachment_show', :f => attachment %>
        <% end %>
        <div id="attachment_fields" class="col-md-2 margin-top-10 " style="padding-right: 2px;" >
          <%= link_to_add_association 'add file', f, :document_attachments, class: 'btn btn-success pull-right', partial: 'attachments/attachment_fields' %>
        </div>
      </div>

      <div class="form-group" >
        <div class="col-md-11">
          <%= link_to t('button_cancel'), back_url(f.object), class: 'btn btn-warning pull-right' %>
          <%= f.submit t(:button_save), class: 'btn btn-primary pull-right' %>
        </div>
      </div>
  <% end %>
</fieldset>

app/views/documents/_list.html.erb
<table class="table table-bordered table-responsive">
  <thead>
  <tr>
    <th><%= t(:title) %></th>
    <th><%= t(:document_type)%></th>
    <th><%= ( :date) %></th>
   </tr>
  </thead>

  <tbody>
  <% if documents.any? %>
      <% documents.each do |document| %>
          <tr>
            <td><%= link_to document.title, document_path(document) %></td>
            <td><%= document.document_type %></td>
            <td><%= document.date %></td>
          </tr>
      <% end %>
  <% else %>
      <tr align="center">
        <td colspan="9"><%= t('label_no_data') %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/documents/edit.html.erb
<section id="widget-grid" class="show_customer_account">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     document: @document,
                     wid_id: 'document',
                     wid_title: 'Editing Document'
                 } %>
    </article>
  </div>
</section>

app/views/documents/index.html.erb
<h1>Documents</h1>

<%= link_to( 'New Document', new_document_path, class: 'btn btn-primary pull-right margin-bottom-10')  if can?(:create_documents, :manage_roles, :manage_documents)%>
<%= render partial: 'documents/list', locals: {documents: @documents} %>

app/views/documents/new.html.erb
<section id="widget-grid" class="show_customer_account">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     document: @document,
                     wid_id: 'document',
                     wid_title: 'New Document'
                 } %>
    </article>
  </div>
</section>

app/views/documents/show.html.erb
<div class="col-xs-12 btn-edition">
  <%= link_to 'Delete',  document_path(@document), class: 'btn btn-danger pull-right' ,
              :method => :delete,
              :data => {:confirm => t(:text_are_you_sure)}
  %>
  <%= link_to 'Edit', edit_document_path(@document), class: 'btn btn-success pull-right' %>
  <%= link_to t('button_cancel'), back_url(@document), class: 'btn btn-warning pull-right' %>
  <%= link_to t('button_print'), document_path(@document, format: 'pdf'), class: 'btn btn-primary pull-right' %>
</div>
<div class="col-xs-12">

  <p>
    <strong>Title:</strong>
    <%= @document.title %>
  </p>


 <p>
    <strong>Description:</strong>
    <%= @document.description.html_safe %>
  </p>

  <p>
    <strong>Document type:</strong>
    <%= @document.document_type %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @document.date %>
  </p>

  <p>
    <strong><%= t('attachments') %>:</strong>
    <% @document.document_attachments.each do |attachment| %>
        <%= render 'attachments/attachment_show_only', :attachment => attachment %>
    <% end %>
  </p>
</div>