config/routes.rb
Rails.application.routes.draw do
  resources :checklist_notes, except: [:index], controller: :notes
  resources :survey_notes, except: [:index], controller: :notes
  resources :case_notes, except: [:index], controller: :notes
  resources :task_notes, except: [:index], controller: :notes
  resources :notes, except: [:index]

  resources :cases do
    member do
      get 'delete_sub_case_relation'
      get 'delete_relation'
      match 'new_relation', via: [:post, :get]
      match 'new_assign', via: [:post, :get]
      match 'new_assign_survey', via: [:post, :get]
    end
  end
  resources :attempts, :only => [:new, :create, :index]
  get 'pivot_table/index'

  get 'settings/edit'
  get 'home/index'
  root to: "home#index"
  get 'home/all_informations', as: 'all_informations'

  get 'home/pivottable'

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }

  # Routes For Normal users
  resources :core_demographics, only: [:show]
  resources :departments do
    resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :contacts do
    resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :affiliations do
    resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
  end
  resources :organizations do
    resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :other_skills
  resources :clearances
  resources :certifications
  resources :educations
  resources :languages
  resources :positions
  resources :tasks do
    member do
      post 'new_note'
      get 'add_note'
      get 'delete_sub_task_relation'
    end
  end
  resources :documents


  resources :surveys do
    member do
      post   'answer'
      get    'new_note'
      get    'edit_answer'
      post   'edit_answer'
      delete 'delete_answer'
    end

    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :survey_survey,  controller: :surveys


  # Routes For Admin
  resources :checklist_templates, controller: :checklists do
    member do
      match 'save', via: [:patch, :put, :post]
      get 'new_note'
    end
    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :users, only: [:index, :show, :destroy] do
    member do
      put 'change_password'
      put 'change_basic_info'
      post 'image_upload'
      get 'remove_image'
    end

    resources :core_demographics, only: [:create, :update]
    resources :job_details, only: [:create, :update]
    resources :user_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :employees, except: [:edit] do
    member do
      get 'log_in'
    end

    get 'home/index', as: 'home'
    resources :educations
    resources :tasks
    resources :languages
    resources :positions
    resources :other_skills
    resources :clearances
    resources :certifications
    resources :departments do
      resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :contacts do
      resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :affiliations do
      resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
    end
    resources :organizations do
      resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :documents
  end

  resources :enumerations
  resources :roles
  resources :settings, only: [:index, :create] do
    collection do
      post 'set_modules'
    end
  end
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  has_many :users
  belongs_to :user
  belongs_to :affiliation_type
  has_one :affiliation_extend_demography, :dependent => :destroy


  has_many :affiliation_attachments, foreign_key: :owner_id
  accepts_nested_attributes_for :affiliation_attachments, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name
  after_save :send_notification

  def send_notification
    UserMailer.affiliation_notification(self).deliver_now
  end

  def affiliation_type
    if affiliation_type_id
      super
    else
      AffiliationType.default
    end
  end

  def visible?
    User.current == user or User.current.allowed_to?(:edit_affiliations) or User.current.allowed_to?(:manage_affiliations)
  end

  def to_s
    name
  end

  def self.safe_attributes
    [:name, :affiliation_type_id, :note, :user_id ]
  end

  def extend_informations
    affiliation_extend_demography || AffiliationExtendDemography.new(affiliation_id: self.id)
  end

  def to_pdf(pdf)
    pdf.font_size(25){  pdf.text "Affiliation ##{id}", :style => :bold}
    user.to_pdf_brief_info(pdf)
    pdf.text "<b>name: </b> #{name}", :inline_format =>  true
    pdf.text "<b>Affiliation type: </b> #{affiliation_type}", :inline_format =>  true
    pdf.text "<b>Note: </b> #{ActionView::Base.full_sanitizer.sanitize(note)}", :inline_format =>  true
  end

  def for_mail
    output = ""
    output<< "<h2>Affiliation ##{id} </h2>"
    output<< "<b>name: </b> #{name}<br/>"
    output<< "<b>Affiliation type: </b> #{affiliation_type}<br/>"
    output<< "<b>Note: </b> #{note}<br/>"

    output.html_safe
  end

end

app/models/enumerations/affiliation_type.rb
class AffiliationType < Enumeration
  has_many :affiliations

  OptionName = :enumeration_affiliation_type

  def option_name
    OptionName
  end

  def objects
    Affiliation.where(:affiliation_type_id => self.id)
  end

  def objects_count
    objects.count
  end

  def transfer_relations(to)
    objects.update_all(:affiliation_type_id => to.id)
  end
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  before_action  :authenticate_user!
  before_action :set_affiliation, only: [:show, :edit, :update, :destroy]
  # before_action :find_optional_user
  before_action :authorize, only: [:new, :create]
  before_action :authorize_edit, only: [:edit, :update]
  before_action :authorize_delete, only: [:destroy]


  # GET /affiliations
  # GET /affiliations.json
  def index
    @affiliations = Affiliation.visible(:view_affiliations)
  end

  # GET /affiliations/1
  # GET /affiliations/1.json
  def show
  end

  # GET /affiliations/new
  def new
    @affiliation = Affiliation.new user_id: @user.id
  end

  # GET /affiliations/1/edit
  def edit
  end

  # POST /affiliations
  # POST /affiliations.json
  def create
    @affiliation = Affiliation.new(affiliation_params)

    respond_to do |format|
      if @affiliation.save
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully created.' }
        format.json { render :show, status: :created, location: @affiliation }
      else
        format.html { render :new }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliations/1
  # PATCH/PUT /affiliations/1.json
  def update
    respond_to do |format|
      if @affiliation.update(affiliation_params)
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully updated.' }
        format.json { render :show, status: :ok, location: @affiliation }
      else
        format.html { render :edit }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliations/1
  # DELETE /affiliations/1.json
  def destroy
    @affiliation.destroy
    respond_to do |format|
      format.html { redirect_to affiliations_url, notice: 'Affiliation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_404
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affiliation_params
      params.require(:affiliation).permit(Affiliation.safe_attributes)
    end

  def authorize_edit
    raise Unauthorized unless @affiliation.can?(:edit_affiliations, :manage_affiliations, :manage_roles)
  end

  def authorize_delete
    raise Unauthorized unless @affiliation.can?(:delete_affiliations, :manage_affiliations, :manage_roles)
  end
  
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/_form.html.erb
<%= form_for(affiliation, html: { class: 'form-horizontal' }) do |f| %>
    <% if affiliation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(affiliation.errors.count, "error") %> prohibited this affiliation from being saved:</h2>

          <ul>
            <% affiliation.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <fieldset>
      <legend>Set Affiliation</legend>
      <%= f.hidden_field :user_id %>
      <div class="form-group">
        <%= f.label t('label_name'), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t('affiliation_type'), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.select :affiliation_type_id, options_helper(AffiliationType, affiliation.affiliation_type_id) ,{}, {class: 'form-control'} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t(:label_note), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_area :note, class: 'form-control ckeditor' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-12">
          <%= f.label t(:attachments) , class: 'col-md-2 control-label' %>
        </div>
        <%= f.simple_fields_for :affiliation_attachments do |attachment| %>
            <%= render 'attachments/attachment_show', :f => attachment %>
        <% end %>
        <div id="attachment_fields" class="col-md-2 margin-top-10 " style="padding-right: 2px;" >
          <%= link_to_add_association 'add file', f, :affiliation_attachments, class: 'btn btn-success pull-right', partial: 'attachments/attachment_fields' %>
        </div>
      </div>

      <div class="form-group" >
        <div class="col-md-11">
          <%= link_to t('button_cancel'), affiliations_path, class: 'btn btn-warning pull-right' %>
          <%= f.submit t('button_save'), class: 'btn btn-primary pull-right' %>
        </div>
      </div>
    </fieldset>
<% end %>

app/views/affiliations/_list.html.erb
<table class="table table-bordered table-responsive">
  <thead>
  <tr>
    <th><%= t :label_name %></th>
    <th><%= t :affiliation_type %></th>
 </tr>
  </thead>

  <tbody>
  <% if affiliations.any? %>
      <% affiliations.each do |affiliation| %>
          <tr>
            <td><%= link_to affiliation.name, affiliation %></td>
            <td><%= affiliation.affiliation_type %></td>
            </tr>
      <% end %>
  <% else %>
      <tr align="center">
        <td colspan="11"><%= t('label_no_data') %></td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/affiliations/edit.html.erb
<section id="widget-grid" class="show_customer_account">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     affiliation: @affiliation,
                     wid_id: 'affiliation',
                     wid_title: 'Edit Affiliation'
                 } %>
    </article>
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'extend_demographies/form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     wid_id: 'extend_demography',
                     wid_title: 'Affiliations informations',
                     extend_demography: @affiliation.extend_informations
                 } %>
    </article>
  </div>
</section>

app/views/affiliations/index.html.erb
<h1><%= t(:affiliation) %></h1>

<%= link_to( t(:new_affiliation), new_affiliation_path, class: 'btn btn-primary pull-right margin-bottom-10') if can?(:create_affiliations, :manage_affiliations, :manage_roles) %>
<%= render partial: 'list', locals:{affiliations: @affiliations}  %>

app/views/affiliations/new.html.erb
<section id="widget-grid" class="show_customer_account">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     affiliation: @affiliation,
                     wid_id: 'affiliation',
                     wid_title: 'New affiliation'
                 } %>
    </article>
  </div>
</section>

app/views/affiliations/show.html.erb
<div class="col-xs-12 btn-edition">
  <%= link_to 'Delete',  affiliation_path(@affiliation), class: 'btn btn-danger pull-right',
              :method => :delete,
              :data => {:confirm => t(:text_are_you_sure)}
  %>
  <%= link_to 'Edit', edit_affiliation_path(@affiliation), class: 'btn btn-success pull-right' %>
  <%= link_to t('button_cancel'), affiliations_path, class: 'btn btn-warning pull-right' %>
  <%= link_to t('button_print'), affiliation_path(@affiliation, format: 'pdf'), class: 'btn btn-primary pull-right' %>
</div>
<div class="col-xs-12">
  <p>
    <strong>Name:</strong>
    <%= @affiliation.name %>
  </p>

  <p>
    <strong>Affiliation type:</strong>
    <%= @affiliation.affiliation_type %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= @affiliation.note.html_safe %>
  </p>


  <p>
    <strong><%= t('attachments') %>:</strong>
    <% @affiliation.affiliation_attachments.each do |attachment| %>
        <%= render 'attachments/attachment_show_only', :attachment => attachment %>
    <% end %>
  </p>

  <%= render_extend_demography_information(@affiliation.affiliation_extend_demography) %>
</div>