config/routes.rb
Rails.application.routes.draw do
  resources :checklist_notes, except: [:index], controller: :notes
  resources :survey_notes, except: [:index], controller: :notes
  resources :case_notes, except: [:index], controller: :notes
  resources :task_notes, except: [:index], controller: :notes
  resources :notes, except: [:index]

  resources :cases do
    member do
      get 'delete_sub_case_relation'
      get 'delete_relation'
      match 'new_relation', via: [:post, :get]
      match 'new_assign', via: [:post, :get]
      match 'new_assign_survey', via: [:post, :get]
    end
  end
  resources :attempts, :only => [:new, :create, :index]
  get 'pivot_table/index'

  get 'settings/edit'
  get 'home/index'
  root to: "home#index"
  get 'home/all_informations', as: 'all_informations'

  get 'home/pivottable'

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }

  # Routes For Normal users
  resources :core_demographics, only: [:show]
  resources :departments do
    resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :contacts do
    resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :affiliations do
    resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
  end
  resources :organizations do
    resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :other_skills
  resources :clearances
  resources :certifications
  resources :educations
  resources :languages
  resources :positions
  resources :tasks do
    member do
      post 'new_note'
      get 'add_note'
      get 'delete_sub_task_relation'
    end
  end
  resources :documents


  resources :surveys do
    member do
      post   'answer'
      get    'new_note'
      get    'edit_answer'
      post   'edit_answer'
      delete 'delete_answer'
    end

    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :survey_survey,  controller: :surveys


  # Routes For Admin
  resources :checklist_templates, controller: :checklists do
    member do
      match 'save', via: [:patch, :put, :post]
      get 'new_note'
    end
    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :users, only: [:index, :show, :destroy] do
    member do
      put 'change_password'
      put 'change_basic_info'
      post 'image_upload'
      get 'remove_image'
    end

    resources :core_demographics, only: [:create, :update]
    resources :job_details, only: [:create, :update]
    resources :user_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :employees, except: [:edit] do
    member do
      get 'log_in'
    end

    get 'home/index', as: 'home'
    resources :educations
    resources :tasks
    resources :languages
    resources :positions
    resources :other_skills
    resources :clearances
    resources :certifications
    resources :departments do
      resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :contacts do
      resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :affiliations do
      resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
    end
    resources :organizations do
      resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :documents
  end

  resources :enumerations
  resources :roles
  resources :settings, only: [:index, :create] do
    collection do
      post 'set_modules'
    end
  end
end

app/models/enumerations/survey_type.rb
class SurveyType < Enumeration
  has_many :surveys

  OptionName = :enumeration_survey_type

  def option_name
    OptionName
  end

  def objects
    Survey::Survey.where(:survey_type_id => self.id)
  end

  def objects_count
    objects.count
  end

  def transfer_relations(to)
    objects.update_all(:survey_type_id => to.id)
  end
end

app/models/survey/answer.rb
class Survey::Answer < ActiveRecord::Base

  self.table_name = "survey_answers"

  acceptable_attributes :attempt, :option, :correct, :option_id, :question, :question_id

  # associations
  belongs_to :attempt
  belongs_to :option
  belongs_to :question

  # validations
  validates :option_id, :question_id, :presence => true
  validates :option_id, :uniqueness => { :scope => [:attempt_id, :question_id] }

  # callbacks
  after_create :characterize_answer

  def value
    points = (self.option.nil? ? Survey::Option.find(option_id) : self.option).weight
    correct?? points : - points
  end

  def correct?
    self.correct ||= self.option.correct?
  end

  private

  def characterize_answer
    update_attribute(:correct, option.correct?)
  end

end

app/models/survey/attempt.rb
class Survey::Attempt < ActiveRecord::Base

  self.table_name = "survey_attempts"

  acceptable_attributes :winner, :survey, :survey_id,
    :participant,
    :participant_id,
    :answers_attributes => ::Survey::Answer::AccessibleAttributes

  # relations
  belongs_to :survey
  belongs_to :participant, :polymorphic => true
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers,
    :reject_if => ->(q) { q[:question_id].blank? || q[:option_id].blank? }

  # validations
  validates :participant_id, :participant_type, :presence => true
  validate :check_number_of_attempts_by_survey

  #scopes
  scope :wins,   -> { where(:winner => true) }
  scope :looses, -> { where(:winner => false) }
  scope :scores, -> { order("score DESC") }
  scope :for_survey, ->(survey) { where(:survey_id => survey.id) }
  scope :exclude_survey,  ->(survey) { where("NOT survey_id = #{survey.id}") }
  scope :for_participant, ->(participant) {
    where(:participant_id => participant.try(:id), :participant_type => participant.class.base_class)
  }

  # callbacks
  before_create :collect_scores

  def correct_answers
    return self.answers.where(:correct => true)
  end

  def incorrect_answers
    return self.answers.where(:correct => false)
  end

  def self.high_score
    return scores.first.score
  end

  private

  def check_number_of_attempts_by_survey
    attempts = self.class.for_survey(survey).for_participant(participant)
    upper_bound = self.survey.attempts_number

    if attempts.size >= upper_bound && upper_bound != 0
      errors.add(:survey_id, "Number of attempts exceeded")
    end
  end

  def collect_scores
    self.score = self.answers.map(&:value).reduce(:+) || 0
  end
end

app/models/survey/option.rb
class Survey::Option < ActiveRecord::Base

  self.table_name = "survey_options"

  acceptable_attributes :text, :correct, :weight

  #relations
  belongs_to :question

  # validations
  validates :text, :presence => true, :allow_blank => false

  # scopes
  scope :correct,   -> { where(:correct => true)  }
  scope :incorrect, -> { where(:correct => false) }

  # callbacks
  before_create :default_option_weight

  def to_s
    return self.text
  end

  def correct?
    return (self.correct == true)
  end

  private

  def default_option_weight
    self.weight = 1 if correct? && self.weight == 0
  end

end

app/models/survey/question.rb
class Survey::Question < ActiveRecord::Base

  self.table_name = "survey_questions"

  acceptable_attributes :text, :survey, :options_attributes => Survey::Option::AccessibleAttributes

  # relations
  belongs_to :survey
  has_many   :options, :dependent => :destroy
  accepts_nested_attributes_for :options,
    :reject_if => ->(a) { a[:text].blank? },
    :allow_destroy => true

  # validations
  validates :text, :presence => true, :allow_blank => false

  def correct_options
    return options.correct
  end

  def incorrect_options
    return options.incorrect
  end
end

app/models/survey/survey.rb
class Survey::Survey < ActiveRecord::Base

  self.table_name = "survey_surveys"

  acceptable_attributes :name, :description,
                        :finished,
                        :active,
                        :attempts_number,
                        :survey_type_id,
                        :questions_attributes => Survey::Question::AccessibleAttributes

  # relations
  has_many :attempts,  :dependent => :destroy
  has_many :questions, :dependent => :destroy
  has_many :survey_users,  :dependent => :destroy
  has_many :survey_notes, foreign_key: :owner_id, :dependent => :destroy
  has_many :survey_cases, :dependent => :destroy

  belongs_to :survey_type, optional: true

  accepts_nested_attributes_for :questions,
                                :reject_if => ->(q) { q[:text].blank? },
                                :allow_destroy => true

  # scopes
  scope :active,   -> { where(:active => true) }
  scope :inactive, -> { where(:active => false) }
  scope :not_related, -> {where(related_to_id: nil)}


  # validations
  validates :attempts_number, :numericality => { :only_integer => true, :greater_than => -1 }
  validates :description, :name, :presence => true, :allow_blank => false
  validate  :check_active_requirements


  def to_s
    name
  end

  def survey_type
    if survey_type_id
      super
    else
      SurveyType.default
    end
  end
  # returns all the correct options for current surveys
  def correct_options
    return self.questions.map(&:correct_options).flatten
  end

  # returns all the incorrect options for current surveys
  def incorrect_options
    return self.questions.map(&:incorrect_options).flatten
  end

  def available_for_participant?(participant)
    current_number_of_attempts = self.attempts.for_participant(participant).size
    upper_bound = self.attempts_number
    return !((current_number_of_attempts >= upper_bound) && (upper_bound != 0))
  end

  def avaliable_for_participant?(participant)
    warn "[DEPRECATION] avaliable_for_participant? is deprecated. Please use available_for_participant? instead"
    available_for_participant?(participant)
  end

  def to_pdf(pdf)
    pdf.font_size(25){  pdf.text "Survey ##{id}", :style => :bold}
    pdf.text "<b>name: </b> #{name}", :inline_format =>  true
    pdf.text "<b>Description: </b> #{ActionView::Base.full_sanitizer.sanitize(description)}", :inline_format =>  true
    self.questions.each_with_index do |question, index|
      pdf.text "<b>Q#{index+1}: </b>", :inline_format =>  true
      pdf.text "<b>#{question.text}: </b>", :inline_format =>  true
      question.options.each do |option|
        pdf.text "-#{option.text}: </b>", :inline_format =>  true
      end
    end
  end

  private

  # a surveys only can be activated if has one or more questions
  def check_active_requirements
    errors.add(:active, "Survey without questions cannot be activated") if self.active && self.questions.empty?
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_filter :load_survey, :only => [:show, :edit, :update, :new_note, :destroy]

  def index
    if User.current.admin?
      @surveys = Survey::Survey.not_related.order('id DESC').paginate(page: params[:page], per_page: 25)
    else
      @surveys = Survey::Survey.not_related.includes(:survey_users).
          references(:survey_users).where("#{SurveyUser.table_name}.assigned_to_id = ?", User.current.id ).order('name DESC').paginate(page: params[:page], per_page: 25)
    end
  end

  def new_assign
    if request.post?
      @survey = SurveyUser.new(params.require(:survey_user).permit!)

      if @survey.save
        redirect_to surveys_path
      else
        @surveys = Survey::Survey.order('name ASC') - Survey::Survey.where(id: SurveyUser.where(assigned_to_id: User.current.id).pluck(:survey_id))
      end
    else
      @surveys = Survey::Survey.order('name ASC') - Survey::Survey.where(id: SurveyUser.where(assigned_to_id: User.current.id).pluck(:survey_id))
      @survey = SurveyUser.new(assigned_to_id: User.current.id)

    end
  end

  def new
    @survey = Survey::Survey.new(  related_to_id: params[:related_to],
                                   related_to_type: params[:type])
  end

  def new_note
    @note = SurveyNote.new(user_id: User.current.id, owner_id: @survey.id)
  end

  def create
    @survey = Survey::Survey.new(survey_params)
    if @survey.valid? && @survey.save
      default_redirect
    else
      render :action => :new
    end
  end

  def edit
  end

  def show
    @notes = @survey.survey_notes
  end

  def update
    if @survey.update_attributes(survey_params)
      default_redirect
    else
      render :action => :edit
    end
  end

  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def default_redirect
    redirect_to back_url, alert: I18n.t("surveys_controller.#{action_name}")
  end

  def load_survey
    @survey = Survey::Survey.find(params[:id])
  end

  def survey_params
    rails4? or rails5? ? params_whitelist : params[:survey_survey]
  end

  def params_whitelist
    params.require(:survey_survey).permit(Survey::Survey::AccessibleAttributes)
  end

  def back_url
    if @survey.case
      case_url(@survey.case)
    else
      surveys_url
    end
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
  def link_to_remove_field(name, f)
    f.hidden_field(:_destroy) +
    __link_to_function(raw(name), "removeField(this)", :id =>"remove-attach")
  end

  def new_survey
    new_survey_path
  end

  def edit_survey(resource)
    edit_survey_path(resource)
  end

  def survey_scope(resource)
    if action_name =~ /new|create/
      surveys_path(resource)
    elsif action_name =~ /edit|update/
      survey_path(resource)
    end
  end

  def new_attempt(params= {})
    new_attempt_path(params)
  end

  def attempt_scope(resource)
    if action_name =~ /new|create/
     attempts_path(resource)
    elsif action_name =~ /edit|update/
      attempt_path(resource)
    end
  end

  def link_to_add_field(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,:child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    __link_to_function(name, "addField(this, \"#{association}\", \"#{escape_javascript(fields)}\")",
    :id=>"add-attach",
    :class=>"btn btn-small btn-info")
  end

  private

  def __link_to_function(name, on_click_event, opts={})
    link_to(name, '#', opts.merge(onclick: on_click_event))
  end
end

app/views/surveys/_form.html.erb
<fieldset>
  <legend>Survey</legend>
  <%= form_for(@survey, :url => survey_scope(@survey), html: { class: 'form-horizontal' }) do |f| %>

      <% if f.object.errors.messages.any? %>
          <ul>
            <% f.object.errors.messages.each_pair do |field, msg| %>
                <li>
                  <%= "#{field} - #{msg}" %>
                </li>
            <% end -%>
          </ul>
      <% end -%>

      <%= f.hidden_field :related_to_type %>
      <%= f.hidden_field :related_to_id %>

      <div class="form-group">
        <%= f.label 'Name', class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :survey_type , class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.select :survey_type_id, options_for_select(SurveyType.active.pluck(:name, :id), selected: f.object.survey_type.try(:id)), {} , {class: 'form-control'} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :attempts_number, class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :attempts_number, class: 'form-control' %>
        </div>
      </div>


      <div class="form-group">
        <%= f.label 'Active', class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.select :active,["true", "false"] , {}, {class: 'col-xs-12 use_select2', style: 'padding: 0' } %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t(:description), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_area :description , class: 'form-control ckeditor' %>
        </div>
      </div>


      <div class="form-group">
        <div class="col-md-12">
          <%= f.fields_for :questions do |builder| %>
              <%= render "question_fields", :f => builder %>
          <% end %>
          <%= link_to_add_association "Add a new Question", f, :questions,  class: 'btn btn-success margin-top-10' %>
        </div>
      </div>



      <div class="form-group" >
        <div class="col-md-11">
          <%= f.submit class: 'btn btn-primary pull-right' %>
        </div>
      </div>
  <% end -%>
</fieldset>

<script type="text/javascript">
  // remove attachment field
  function removeField(link) {
    $(link).prev("input[type=hidden]").val("true");
    tag = $(link).closest("li")
    tag.hide("fade in").addClass("deleted");
  }

  // add attachment field
  function addField(link, association, content) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    var html = $(content.replace(regexp, new_id)).hide();
    html.appendTo($(link).closest("div.field").find("ul").first()).slideDown("slow");
  }
</script>

app/views/surveys/_list.html.erb
<table class="table table-responsive table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Survey type</th>
    <th>Attempts</th>
    <th>Last updated</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% if @surveys.any? %>
      <% @surveys.each do |survey| %>
          <tr>
            <td><%= link_to survey.name, survey_path(survey) %></td>
            <td><%= survey.survey_type %></td>
            <td><%= survey.attempts.where(participant_id: User.current.id).count %></td>
            <td><%= survey.attempts.last.answers.last.updated_at.strftime('%d/%m/%y %H:%M') rescue '' %></td>

            <% if params[:controller] == 'cases' %>
                <td><%= link_to 'New attempt', new_attempt_path(survey_id: survey.id, c: params[:controller], case_id: @case.id) %> </td>
                <td><%= link_to 'Show attempts', attempts_path(survey_id: survey.id, case_id: @case.id) %> </td>
            <% else %>
                <td><%= link_to 'New attempt', new_attempt_path(survey_id: survey.id) %> </td>
                <td><%= link_to 'Show attempts', attempts_path(survey_id: survey.id) %> </td>
            <% end %>


            <% if User.current.admin? %>
                <td><%= edit_link edit_survey_path survey %></td>
            <% end %>

          </tr>
      <% end %> <% else %>
      <tr align="center">
        <td colspan="11"><%= t('label_no_data') %></td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/surveys/_new_assign.html.erb
<fieldset>
  <legend>Survey</legend>
  <%= simple_form_for(survey, url: new_assign_surveys_path, html: {method: 'post', class: 'form-horizontal' }) do |f| %>
      <% data = survey
         if data.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(data.errors.count, "error") %> :</h2>

            <ul>
              <% data.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <%= f.hidden_field :assigned_to_id %>


      <div class="form-group">
        <%= f.label 'Survey', class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.select :survey_id, options_for_select(@surveys.map{|c| [c.name, c.id]  }, selected: f.object.survey_id),{}, {class: 'form-control'} %>
        </div>
      </div>


      <div class="form-group" >
        <div class="col-md-11">
          <%= link_to t('button_cancel'), surveys_path, class: 'btn btn-warning pull-right' %>
          <%= f.submit t('button_save'), class: 'btn btn-primary pull-right' %>
        </div>
      </div>
  <% end %>
</fieldset>

app/views/surveys/_option_fields.html.erb
<div class="nested-fields row">

<div class="form-group">
  <%= f.label 'Text', class: 'col-md-3 control-label' %>
  <div class="col-md-5">
    <%= f.text_field :text, class: 'form-control' %>
  </div>
  <div class="col-md-4">
    <%= f.label :correct, class: 'col-md-2 control-label' %>
    <div class="col-md-9">
      <%= f.check_box :correct %>
      <%= link_to_remove_association "<i class='fa fa-trash-o'></i>".html_safe , f, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

</div>

app/views/surveys/_question_fields.html.erb
<div class="col-md-12">
  <legend>Question <%= link_to_remove_association "Remove Question", f, class: 'btn btn-warning pull-right' %></legend>
  <div class="field">
    <div class="form-group">
      <%= f.label 'Text', class: 'col-md-2 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :text, class: 'form-control' %>
      </div>
    </div>


    <%= f.fields_for :options do |builder| %>
        <%= render "option_fields", :f => builder %>
    <% end -%>
    <div class="options">
      <%= link_to_add_association "Add a new Option", f, :options,  class: 'btn btn-success margin-bottom-10' %>
    </div>
  </div>
</div>

app/views/surveys/_show.html.erb
<div class="survey-title">
  <h2><%= survey.name %></h2>
  <p><small><%= survey.description.html_safe %></small></p>
  <ul>
    <% survey.questions.each_with_index do |question, index| %>
        <li>
          <p><%= question.text %></p>
         <% question.options.each do |option| %>
             <p> <%= option.text %></p>
          <% end -%>
        </li>
    <% end -%>
  </ul>
</div>

app/views/surveys/edit.html.erb
<h2>Edit Survey</h2>
<%= render 'form' %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>
<% if User.current.admin? %>
    <%= link_to( 'New Survey', new_survey_path, class: 'btn btn-primary pull-right margin-bottom-10')%>
<% else %>
    <%= link_to( 'New Survey', new_assign_surveys_path, class: 'btn btn-primary pull-right margin-bottom-10')%>
<% end %>
<%= render 'list' %>
<%= will_paginate @surveys, renderer: BootstrapPagination::Rails %>

app/views/surveys/new.html.erb
<h2>New Survey</h2>
<%= render 'form' %>

app/views/surveys/new_assign.html.erb
<section id="widget-grid" class="checklists_account">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'new_assign',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     survey: @survey,
                     wid_id: 'survey',
                     wid_title: 'New assign for survey'
                 } %>
    </article>
  </div>
</section>

app/views/surveys/new_note.html.erb
<section id="widget-grid1" class="form_note">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'notes/form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     note: @note,
                     wid_id: 'note_form',
                     wid_title: 'Add note'
                 } %>
    </article>
  </div>
</section>

app/views/surveys/show.html.erb
<div class="col-xs-12 btn-edition">
  <%= link_to 'Delete',  survey_path(@survey), class: 'btn btn-danger pull-right',
              :method => :delete,
              :data => {:confirm => t(:text_are_you_sure)}
  %>
  <%= link_to 'Edit', edit_survey_path(@survey), class: 'btn btn-success pull-right' %>
  <%= link_to t('button_cancel'), :back, class: 'btn btn-warning pull-right' %>
  <%= link_to t('button_print'), survey_path(@survey, format: 'pdf'), class: 'btn btn-primary pull-right' %>
  <%= link_to 'New note', new_note_survey_path(@survey), class: 'btn btn-success pull-right' %>
</div>
<section id="widget-grid" class="form_note_list">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'show',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     survey: @survey,
                     wid_id: 'survey',
                     wid_title: 'Survey'
                 } %>
    </article>
  </div>
</section>

<% if @notes.any? %>
    <section id="widget-grid" class="form_note_list">
      <div class="row">
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <%= render partial: 'notes/notes',
                     layout: 'shared/smart_widget_wrapper',
                     locals: {
                         notes: @notes,
                         wid_id: 'note_lists',
                         wid_title: 'Notes'
                     } %>
        </article>
      </div>
    </section>

<% end %>