config/routes.rb
Rails.application.routes.draw do
  resources :checklist_notes, except: [:index], controller: :notes
  resources :survey_notes, except: [:index], controller: :notes
  resources :case_notes, except: [:index], controller: :notes
  resources :task_notes, except: [:index], controller: :notes
  resources :notes, except: [:index]

  resources :cases do
    member do
      get 'delete_sub_case_relation'
      get 'delete_relation'
      match 'new_relation', via: [:post, :get]
      match 'new_assign', via: [:post, :get]
      match 'new_assign_survey', via: [:post, :get]
    end
  end
  resources :attempts, :only => [:new, :create, :index]
  get 'pivot_table/index'

  get 'settings/edit'
  get 'home/index'
  root to: "home#index"
  get 'home/all_informations', as: 'all_informations'

  get 'home/pivottable'

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }

  # Routes For Normal users
  resources :core_demographics, only: [:show]
  resources :departments do
    resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :contacts do
    resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end
  resources :affiliations do
    resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
  end
  resources :organizations do
    resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :other_skills
  resources :clearances
  resources :certifications
  resources :educations
  resources :languages
  resources :positions
  resources :tasks do
    member do
      post 'new_note'
      get 'add_note'
      get 'delete_sub_task_relation'
    end
  end
  resources :documents


  resources :surveys do
    member do
      post   'answer'
      get    'new_note'
      get    'edit_answer'
      post   'edit_answer'
      delete 'delete_answer'
    end

    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :survey_survey,  controller: :surveys


  # Routes For Admin
  resources :checklist_templates, controller: :checklists do
    member do
      match 'save', via: [:patch, :put, :post]
      get 'new_note'
    end
    collection do
      get 'new_assign'
      post 'new_assign'
    end
  end
  resources :users, only: [:index, :show, :destroy] do
    member do
      put 'change_password'
      put 'change_basic_info'
      post 'image_upload'
      get 'remove_image'
    end

    resources :core_demographics, only: [:create, :update]
    resources :job_details, only: [:create, :update]
    resources :user_extend_demographies, only: [:create, :update], controller: :extend_demographies
  end

  resources :employees, except: [:edit] do
    member do
      get 'log_in'
    end

    get 'home/index', as: 'home'
    resources :educations
    resources :tasks
    resources :languages
    resources :positions
    resources :other_skills
    resources :clearances
    resources :certifications
    resources :departments do
      resources :department_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :contacts do
      resources :contact_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :affiliations do
      resources :affiliation_extend_demographies,  only: [:create, :update], controller: :extend_demographies
    end
    resources :organizations do
      resources :organization_extend_demographies, only: [:create, :update], controller: :extend_demographies
    end
    resources :documents
  end

  resources :enumerations
  resources :roles
  resources :settings, only: [:index, :create] do
    collection do
      post 'set_modules'
    end
  end
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
  belongs_to :education_type
  has_many :education_attachments, foreign_key: :owner_id
  accepts_nested_attributes_for :education_attachments, reject_if: :all_blank, allow_destroy: true

  after_save :send_notification
  def send_notification
    UserMailer.education_notification(self).deliver_now
  end

  def visible?
    User.current == user or User.current.allowed_to?(:edit_educations) or User.current.allowed_to?(:manage_educations)
  end

  def education_type
    if education_type_id
      super
    else
      EducationType.default
    end
  end

  def self.safe_attributes
    [:user_id, :education_type_id, :date_recieved,
     :date_expired, :note,
     education_attachments_attributes: [Attachment.safe_attributes]]
  end

  def to_pdf(pdf)
    pdf.font_size(25){  pdf.text "Education ##{id}", :style => :bold}
    user.to_pdf_brief_info(pdf)
    pdf.text "<b>Education type: </b> #{education_type}", :inline_format =>  true
    pdf.text "<b>Date received: </b> #{date_recieved}", :inline_format =>  true
    pdf.text "<b>Date expired: </b> #{date_expired}", :inline_format =>  true
    pdf.text "<b>Note: </b> #{ActionView::Base.full_sanitizer.sanitize(note)}", :inline_format =>  true
  end

  def for_mail
    output = ""
    output<< "<h2>Education ##{id} </h2>"
    output<<"<b>Education type: </b> #{education_type}<br/>"
    output<<"<b>Date received: </b> #{date_recieved}<br/>"
    output<<"<b>Date expired: </b> #{date_expired}<br/>"
    output<<"<b>Note: </b> #{note}<br/>"

    output.html_safe
  end

end

app/models/enumerations/education_type.rb
class EducationType < Enumeration
  has_many :educations

  OptionName = :enumeration_education_type

  def option_name
    OptionName
  end

  def objects
    Education.where(:education_type_id => self.id)
  end

  def objects_count
    objects.count
  end

  def transfer_relations(to)
    objects.update_all(:education_type_id => to.id)
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action  :authenticate_user!
  before_action :set_education, only: [:show, :edit, :update, :destroy]
  # before_action :find_optional_user
  before_action :authorize, only: [:new, :create]
  before_action :authorize_edit, only: [:edit, :update]
  before_action :authorize_delete, only: [:destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.visible(:view_educations)
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new(user_id: @user.id)
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to educations_url, notice: 'Education was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to educations_url, notice: 'Education was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_404
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(Education.safe_attributes)
    end

  def authorize_edit
    raise Unauthorized unless @education.can?(:edit_educations, :manage_educations, :manage_roles)
  end

  def authorize_delete
    raise Unauthorized unless @education.can?(:delete_educations, :manage_educations, :manage_roles)
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<% if EducationType.count.zero? %>
    <h2>Education Type must be present</h2>
<% end %>
<% if ClearenceType.count.zero? %>
    <h2>Clearence Type must be present</h2>
<% end %>
<%= form_for(education, html: { class: 'form-horizontal' }) do |f| %>
    <% if education.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(education.errors.count, "error") %> prohibited this education from being saved:</h2>

          <ul>
            <% education.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <fieldset>
      <legend>education</legend>

      <%= f.hidden_field :user_id %>
      <div class="form-group">
        <%= f.label t('education_type'), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.select :education_type_id, options_for_select(EducationType.pluck(:name, :id), selected: education.education_type_id), {},{ class: 'form-control'} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t('education_date_received'), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :date_recieved , class: 'form-control date_picker' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t(:education_date_expired), class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :date_expired , class: 'form-control date_picker' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label t(:label_note) , class: 'col-md-2 control-label' %>
        <div class="col-md-9">
          <%= f.text_area :note , class: 'form-control ckeditor' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-12">
          <%= f.label t(:attachments) , class: 'col-md-2 control-label' %>
        </div>
        <%= f.simple_fields_for :education_attachments do |attachment| %>
            <%= render 'attachments/attachment_show', :f => attachment %>
        <% end %>
        <div id="attachment_fields" class="col-md-2 margin-top-10 " style="padding-right: 2px;" >
          <%= link_to_add_association 'add file', f, :education_attachments, class: 'btn btn-success pull-right', partial: 'attachments/attachment_fields' %>
        </div>
      </div>

      <div class="form-group" >
        <div class="col-md-11">
          <%= link_to t('button_cancel'), educations_path, class: 'btn btn-warning pull-right' %>
          <%= f.submit t('button_save'), class: 'btn btn-primary pull-right' %>
        </div>
      </div>
    </fieldset>
<% end %>

app/views/educations/_list.html.erb
<table class="table table-responsive table-bordered">
  <thead>
  <tr>
    <th><%= t :education_type %></th>
    <th><%= t :education_date_received %></th>
    <th><%= t :education_date_expired %></th>
  </tr>
  </thead>

  <tbody>
  <% if educations.any? %>
      <% educations.each do |education| %>
          <tr>
            <td><%= link_to education.education_type, education_path(education) %></td>
            <td><%= education.date_recieved %></td>
            <td><%= education.date_expired %></td>
          </tr>
      <% end %>
  <% else %>
      <tr align="center">
        <td colspan="11"><%= t('label_no_data') %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/educations/edit.html.erb
<%#= link_to 'Show', @education %>
<section id="widget-grid" class="show_customer_account">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     education: @education,
                     wid_id: 'education',
                     wid_title: 'Editing Education'
                 } %>
    </article>
  </div>
</section>

app/views/educations/index.html.erb
<h1>Educations</h1>

<%= link_to( 'New Education', new_education_path, class:'btn btn-primary pull-right margin-bottom-10') if can?(:create_educations, :manage_roles, :manage_educations)%>

<%= render 'list', educations: @educations %>

app/views/educations/new.html.erb
<section id="widget-grid" class="show_customer_account">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'form',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     education: @education,
                     wid_id: 'education',
                     wid_title: 'New Education'
                 } %>
    </article>
  </div>
</section>

app/views/educations/show.html.erb
<div class="col-xs-12 btn-edition">
  <%= link_to 'Delete', education_path(@education), class: 'btn btn-danger pull-right',
              :method => :delete,
              :data => {:confirm => t(:text_are_you_sure)}
  %>
  <%= link_to 'Edit', edit_education_path(@education), class: 'btn btn-success pull-right' %>
  <%= link_to t('button_cancel'), educations_path, class: 'btn btn-warning pull-right' %>
  <%= link_to t('button_print'), education_path(@education, format: 'pdf'), class: 'btn btn-primary pull-right' %>
</div>
<div class="col-xs-12">

<p>
  <strong>Education type:</strong>
  <%= @education.education_type %>
</p>

<p>
  <strong>Date recieved:</strong>
  <%= @education.date_recieved %>
</p>

<p>
  <strong>Date expired:</strong>
  <%= @education.date_expired %>
</p>

<p>
  <strong>Note:</strong>
  <%= @education.note.html_safe %>
</p>


  <p>
    <strong><%= t('attachments') %>:</strong>
    <% @education.education_attachments.each do |attachment| %>
        <%= render 'attachments/attachment_show_only', :attachment => attachment %>
    <% end %>
  </p>
</div>